export const APP_STATES = {
  DEFAULT: "DEFAULT",
  AWAITING_API_RESPONSE: "AWAITING_API_RESPONSE",
  REFRESHING: "REFRESHING",
  ONCLICK: "ONCLICK",
  SCANNING: "SCANNING",
  DATA_READY: "DATA_READY",
  SHOW_PROMPT: "SHOW_PROMPT"
};
